/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package View;

import DAO.AlbumDao;
import DAO.ChanteurDao;
import DAO.ColloboDao;
import DAO.DaoException;
import DAO.DaoFactory;
import DAO.InstruDao;
import DAO.MusicienDao;
import MODEL.Album;
import MODEL.Collobo;
import MODEL.Instru;
import MODEL.Musicien;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Utilisateur
 */
public class JDCollaboInser extends javax.swing.JDialog {
    
     private final ColloboDao daoCollobo = DaoFactory.getInstance().getDAOCollobos();
    private final MusicienDao daoMusicien = DaoFactory.getInstance().getDAOMusicien();
    private final ChanteurDao daoChanteur = DaoFactory.getInstance().getDAOChanteur();
    private final AlbumDao daoAlbum = DaoFactory.getInstance().getDAOAlbum();
    private final InstruDao daoInstru = DaoFactory.getInstance().getDAOInstru();

    /** Creates new form JDPcollaboInser */
    public JDCollaboInser(java.awt.Frame parent, String modal) {
        super(parent, modal);
        initComponents();
        fillComponents();
        getRootPane().setDefaultButton(jButtonAdd);
        setLocation(parent.getX() + parent.getWidth() / 3, parent.getY() + parent.getHeight() / 3);
        setVisible(true);
    }
    
    private void fillComponents() {
        jTextFieldId.setEnabled(false);

        /* charger toutes combobox */
        ArrayList<Album> al = daoAlbum.selectAlbum();
        for (int i = 0; i < al.size(); i++) {
            jComboBoxAlbum.addItem(al.get(i));
        }

        ArrayList<Musicien> musicien = daoMusicien.selectMusicien();
        for (int i = 0; i < musicien.size(); i++) {
            jComboBoxMusicien.addItem(musicien.get(i));
        }

        ArrayList<Instru> instru = daoInstru.selectInstru();
        for (int i = 0; i < instru.size(); i++) {
            jComboBoxinstru.addItem(instru.get(i));
        }

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelup = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanelMenu = new javax.swing.JPanel();
        JLabelIdplan = new javax.swing.JLabel();
        JLabelEmp = new javax.swing.JLabel();
        JLabelPro = new javax.swing.JLabel();
        JLabelIJour = new javax.swing.JLabel();
        jComboBoxMusicien = new javax.swing.JComboBox();
        jComboBoxAlbum = new javax.swing.JComboBox();
        jTextFieldId = new javax.swing.JTextField();
        jComboBoxinstru = new javax.swing.JComboBox();
        jButtonAdd = new javax.swing.JButton();
        jButtonCancel = new javax.swing.JButton();

        setVisible(true);

        jPanelup.setBackground(new java.awt.Color(153, 153, 255));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("     New Collaboration");

        JLabelIdplan.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        JLabelIdplan.setText("Id");

        JLabelEmp.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        JLabelEmp.setText("Album");

        JLabelPro.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        JLabelPro.setText("Musicien");

        JLabelIJour.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        JLabelIJour.setText("Instrument");

        jComboBoxMusicien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxMusicienActionPerformed(evt);
            }
        });

        jComboBoxAlbum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxAlbumActionPerformed(evt);
            }
        });

        jComboBoxinstru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxinstruActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelMenuLayout = new javax.swing.GroupLayout(jPanelMenu);
        jPanelMenu.setLayout(jPanelMenuLayout);
        jPanelMenuLayout.setHorizontalGroup(
            jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMenuLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelMenuLayout.createSequentialGroup()
                        .addComponent(JLabelIJour)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBoxinstru, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanelMenuLayout.createSequentialGroup()
                        .addGroup(jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JLabelEmp)
                            .addComponent(JLabelPro)
                            .addComponent(JLabelIdplan))
                        .addGap(40, 40, 40)
                        .addGroup(jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBoxAlbum, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextFieldId)
                            .addComponent(jComboBoxMusicien, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
        );
        jPanelMenuLayout.setVerticalGroup(
            jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMenuLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(JLabelIdplan)
                    .addComponent(jTextFieldId, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JLabelEmp)
                    .addComponent(jComboBoxAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JLabelPro)
                    .addComponent(jComboBoxMusicien, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLabelIJour)
                    .addComponent(jComboBoxinstru, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jButtonAdd.setBackground(new java.awt.Color(51, 255, 51));
        jButtonAdd.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonAdd.setText("Add Collaboration");
        jButtonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddActionPerformed(evt);
            }
        });

        jButtonCancel.setBackground(new java.awt.Color(255, 51, 51));
        jButtonCancel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonCancel.setText("cancel");
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelupLayout = new javax.swing.GroupLayout(jPanelup);
        jPanelup.setLayout(jPanelupLayout);
        jPanelupLayout.setHorizontalGroup(
            jPanelupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelupLayout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(jButtonAdd)
                .addGap(18, 18, 18)
                .addComponent(jButtonCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanelMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelupLayout.setVerticalGroup(
            jPanelupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelupLayout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonCancel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelup, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelup, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxMusicienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxMusicienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxMusicienActionPerformed

    private void jComboBoxAlbumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxAlbumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxAlbumActionPerformed

    private void jComboBoxinstruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxinstruActionPerformed

    }//GEN-LAST:event_jComboBoxinstruActionPerformed

    private void jButtonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddActionPerformed
        Collobo collabo = new Collobo();
        //collabo.setId((Int)jTextFieldId.getText());
        collabo.setAlbum((Album)jComboBoxAlbum.getSelectedItem());
        collabo.setInstur((Instru) jComboBoxinstru.getSelectedItem());
        collabo.setMusicien((Musicien) jComboBoxMusicien.getSelectedItem());
        // if (jComboBoxAlbum.getSelectedItem().equals("") || jComboBoxinstru.getSelectedItem().equals("")|| jComboBoxMusicien.getSelectedItem().equals("") ) {
            try {
                daoCollobo.insertCollobo(collabo);
                
            } catch (DaoException e) {
                JOptionPane.showMessageDialog(null, "Modification impossible !", "Avertissement", JOptionPane.ERROR_MESSAGE);
            }
            /* } else {
            JOptionPane.showMessageDialog(null, "valeur Remplie tout le formulaire", "Avertissement", JOptionPane.ERROR_MESSAGE);
        }*/
        this.dispose();
    }//GEN-LAST:event_jButtonAddActionPerformed

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonCancelActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLabelEmp;
    private javax.swing.JLabel JLabelIJour;
    private javax.swing.JLabel JLabelIdplan;
    private javax.swing.JLabel JLabelPro;
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JComboBox jComboBoxAlbum;
    private javax.swing.JComboBox jComboBoxMusicien;
    private javax.swing.JComboBox jComboBoxinstru;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanelMenu;
    private javax.swing.JPanel jPanelup;
    private javax.swing.JTextField jTextFieldId;
    // End of variables declaration//GEN-END:variables

}
