/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.beans.PropertyVetoException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Utilisateur
 */
public class JFPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form JFPrincipal
     */
    public JFPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemQuiter = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItemCollobo = new javax.swing.JMenuItem();
        jMenuItemMusicien = new javax.swing.JMenuItem();
        jMenuItemAlbum = new javax.swing.JMenuItem();
        jMenuItemChanteur = new javax.swing.JMenuItem();
        jMenuItemInstru = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 640));
        setSize(new java.awt.Dimension(800, 640));

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 905, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 545, Short.MAX_VALUE)
        );

        jMenuBar1.setBorder(javax.swing.BorderFactory.createTitledBorder("Albums"));

        jMenu1.setText("Fichier");

        jMenuItemQuiter.setText("Quiter");
        jMenuItemQuiter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemQuiterActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemQuiter);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Menu");

        jMenuItemCollobo.setText("collobo");
        jMenuItemCollobo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemColloboActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemCollobo);

        jMenuItemMusicien.setText("Musicien");
        jMenuItemMusicien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemMusicienActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemMusicien);

        jMenuItemAlbum.setText("Album");
        jMenuItemAlbum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAlbumActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemAlbum);

        jMenuItemChanteur.setText("Chanteurs");
        jMenuItemChanteur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemChanteurActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemChanteur);

        jMenuItemInstru.setText("Instrument ");
        jMenuItemInstru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemInstruActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemInstru);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemQuiterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemQuiterActionPerformed
        int rep = JOptionPane.showConfirmDialog(null,"Voulez-vous vraiment quitter ?","Confirmation",JOptionPane.YES_NO_OPTION);
        if (rep == JOptionPane.YES_OPTION)
        {
            System.exit(0);
        }
    }//GEN-LAST:event_jMenuItemQuiterActionPerformed

    private void jMenuItemColloboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemColloboActionPerformed
        jDesktopPane1.removeAll();
        JIFCollabo collobo =new JIFCollabo();
        jDesktopPane1.add(collobo);
        try {
            collobo.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(JFPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        jDesktopPane1.repaint();
    }//GEN-LAST:event_jMenuItemColloboActionPerformed

    private void jMenuItemMusicienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemMusicienActionPerformed
        jDesktopPane1.removeAll();
        JIFMusicien musicien =new JIFMusicien();
        jDesktopPane1.add(musicien);
        try {
            musicien.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(JFPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        jDesktopPane1.repaint();
    }//GEN-LAST:event_jMenuItemMusicienActionPerformed

    private void jMenuItemChanteurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemChanteurActionPerformed
        jDesktopPane1.removeAll();
        JIFChanteur chant =new JIFChanteur();
        jDesktopPane1.add(chant);
        try {
            chant.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(JFPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        jDesktopPane1.repaint();
    }//GEN-LAST:event_jMenuItemChanteurActionPerformed

    private void jMenuItemAlbumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAlbumActionPerformed
        jDesktopPane1.removeAll();
        JIFAlbum album =new JIFAlbum();
        jDesktopPane1.add(album);
        try {
            album.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(JFPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        jDesktopPane1.repaint();
    }//GEN-LAST:event_jMenuItemAlbumActionPerformed

    private void jMenuItemInstruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemInstruActionPerformed
        jDesktopPane1.removeAll();
        JIFInstru instru =new JIFInstru();
        jDesktopPane1.add(instru);
        try {
            instru.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(JFPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        jDesktopPane1.repaint();
    }//GEN-LAST:event_jMenuItemInstruActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new JFPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemAlbum;
    private javax.swing.JMenuItem jMenuItemChanteur;
    private javax.swing.JMenuItem jMenuItemCollobo;
    private javax.swing.JMenuItem jMenuItemInstru;
    private javax.swing.JMenuItem jMenuItemMusicien;
    private javax.swing.JMenuItem jMenuItemQuiter;
    // End of variables declaration//GEN-END:variables
}
