package View;

import controle_table_model.TableModelCollobo;
import DAO.DaoFactory;
import DaoMysql.ColloboDaoMySql;
import MODEL.Album;
import MODEL.Instru;
import MODEL.Musicien;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import DAO.MusicienDao;
import DAO.ColloboDao;
import DAO.AlbumDao;
import DAO.DaoException;
import DAO.InstruDao;
import MODEL.Collobo;
import View.JDCollaboInser;
import java.util.Collections;

public class JIFCollabo extends javax.swing.JInternalFrame {

    private final  DaoFactory factory = DaoFactory.getInstance();
    private  ColloboDao daocollobo = new ColloboDaoMySql(factory);
    private  InstruDao daoInstru = DaoFactory.getInstance().getDAOInstru();
    private  MusicienDao daoMusicien = DaoFactory.getInstance().getDAOMusicien();
    private  AlbumDao daoAlbum = DaoFactory.getInstance().getDAOAlbum();
    private  TableModelCollobo myColloboModel = new TableModelCollobo(daocollobo.selectCollobo());

    public JIFCollabo() {;
        initComponents();
        fillComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new JTable(myColloboModel);
        jPanel6 = new javax.swing.JPanel();
        jButtonAddCollabo = new javax.swing.JButton();
        jButtonUpdateCollabo = new javax.swing.JButton();
        jButtonDelete = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jTextFieldfiltrealbum = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        jPanel5 = new javax.swing.JPanel();
        jComboBoxInstru = new javax.swing.JComboBox();
        jRadioButtonProjet = new javax.swing.JRadioButton();
        jComboBoxMusicien = new javax.swing.JComboBox();
        jRadioButtonMusucien = new javax.swing.JRadioButton();
        jRadioButtonfilter = new javax.swing.JRadioButton();
        jLabelfilter = new javax.swing.JLabel();
        jRadioButtonJour = new javax.swing.JRadioButton();
        jComboBoxAlbum = new javax.swing.JComboBox();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Collaborations"));
        setMinimumSize(new java.awt.Dimension(795, 545));
        setPreferredSize(new java.awt.Dimension(800, 640));
        setVisible(true);

        jTable1.setOpaque(false);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButtonAddCollabo.setBackground(new java.awt.Color(51, 255, 51));
        jButtonAddCollabo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonAddCollabo.setText("new callaboration");
        jButtonAddCollabo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddCollaboActionPerformed(evt);
            }
        });

        jButtonUpdateCollabo.setBackground(new java.awt.Color(255, 204, 0));
        jButtonUpdateCollabo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonUpdateCollabo.setText("Update collabo");
        jButtonUpdateCollabo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdateCollaboActionPerformed(evt);
            }
        });

        jButtonDelete.setBackground(new java.awt.Color(255, 51, 51));
        jButtonDelete.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonDelete.setText("Delete this collabo");
        jButtonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(279, 279, 279)
                .addComponent(jButtonAddCollabo, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonUpdateCollabo)
                .addGap(27, 27, 27)
                .addComponent(jButtonDelete)
                .addContainerGap(203, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAddCollabo)
                    .addComponent(jButtonUpdateCollabo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jButton1.setText("Par Album Decroissante");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Par Album Croissante");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTextFieldfiltrealbum.setToolTipText("");
        jTextFieldfiltrealbum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldfiltrealbumActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("filtre par titre");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jRadioButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldfiltrealbum, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68)
                .addComponent(jButton1)
                .addGap(29, 29, 29)
                .addComponent(jButton2)
                .addGap(38, 38, 38))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldfiltrealbum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButton1)))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 3, Short.MAX_VALUE))
        );

        jComboBoxInstru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxInstruActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButtonProjet);
        jRadioButtonProjet.setText("Nom instru");
        jRadioButtonProjet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonProjetActionPerformed(evt);
            }
        });

        jComboBoxMusicien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxMusicienActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButtonMusucien);
        jRadioButtonMusucien.setText("Nom et Pre musicien");
        jRadioButtonMusucien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMusucienActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButtonfilter);
        jRadioButtonfilter.setText("Aucun");
        jRadioButtonfilter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonfilterActionPerformed(evt);
            }
        });

        jLabelfilter.setText("filter");

        buttonGroup1.add(jRadioButtonJour);
        jRadioButtonJour.setText("Code album");
        jRadioButtonJour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonJourActionPerformed(evt);
            }
        });

        jComboBoxAlbum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxAlbumActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addComponent(jLabelfilter)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButtonfilter)
                .addGap(18, 18, 18)
                .addComponent(jRadioButtonMusucien)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxMusicien, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButtonProjet, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxInstru, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jRadioButtonJour)
                .addGap(18, 18, 18)
                .addComponent(jComboBoxAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jRadioButtonMusucien)
                        .addComponent(jRadioButtonfilter)
                        .addComponent(jLabelfilter)
                        .addComponent(jComboBoxMusicien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jRadioButtonJour)
                        .addComponent(jComboBoxAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jComboBoxInstru, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jRadioButtonProjet)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(295, 295, 295))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonUpdateCollaboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdateCollaboActionPerformed
        if (jTable1.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(this, "Sélectionnez d'abord une ligne svp !", "Avertissement", JOptionPane.ERROR_MESSAGE);
        } else {
            // renvoie l'objet Instru à passer en paramètre
            Collobo plan = myColloboModel.getMyList(jTable1.convertRowIndexToModel(jTable1.getSelectedRow()));

            // récupère la JFrame parente
            JFrame parent = (JFrame) (this.getDesktopPane().getTopLevelAncestor());
            new JDColloboUpdate(parent, "Update Collaboration ", plan);

            // après la modification : rafraîchir les données en relisant la BD
            myColloboModel.setMyList(daocollobo.selectCollobo());
        }
    }//GEN-LAST:event_jButtonUpdateCollaboActionPerformed

    private void jButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteActionPerformed
        if (jTable1.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(null, "Sélectionnez d'abord une ligne svp !", "Avertissement", JOptionPane.ERROR_MESSAGE);
        } else {
            int rep = JOptionPane.showConfirmDialog(this, "Voulez-vous vraiment supprimer cette Collaboration "
                    + myColloboModel.getValueAt(jTable1.convertRowIndexToModel(jTable1.getSelectedRow()), 0) + " ?", "Confirmation", JOptionPane.YES_NO_OPTION);
            if (rep == JOptionPane.YES_OPTION) {
                try {
                    Collobo c = myColloboModel.getMyList(jTable1.convertRowIndexToModel(jTable1.getSelectedRow()));
                    daocollobo.deleteCollobo( c.getId()+"");//myColloboModel.getValueAt(jTable1.convertRowIndexToModel(jTable1.getSelectedRow()), 0)
                } catch (DaoException e) {
                    JOptionPane.showMessageDialog(null, "Suppression impossible !", "Avertissement", JOptionPane.ERROR_MESSAGE);
                }
            }
        }
        // après la suppression : rafraîchir les données en relisant la BD
        myColloboModel.setMyList(daocollobo.selectCollobo());
    }//GEN-LAST:event_jButtonDeleteActionPerformed

    private void jButtonAddCollaboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddCollaboActionPerformed
        // recupere la JFrame parente
        JFrame parent = (JFrame) (this.getDesktopPane().getTopLevelAncestor());
        new JDCollaboInser(parent, "ADD NEW Collaboration");
         myColloboModel.setMyList(daocollobo.selectCollobo());
        // après l'insertion : rafraîchir les données en relisant la BD
        myColloboModel.setMyList(daocollobo.selectCollobo());
    }//GEN-LAST:event_jButtonAddCollaboActionPerformed

    private void jRadioButtonfilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonfilterActionPerformed
        jComboBoxMusicien.setEnabled(false);
        jComboBoxInstru.setEnabled(false);
        jComboBoxAlbum.setEnabled(false);
        jTextFieldfiltrealbum.setEnabled(false);
        myColloboModel.setMyList(daocollobo.selectCollobo());
    }//GEN-LAST:event_jRadioButtonfilterActionPerformed

    private void jRadioButtonMusucienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMusucienActionPerformed
        jComboBoxMusicien.setEnabled(true);
        jComboBoxAlbum.setEnabled(false);
        jComboBoxInstru.setEnabled(false);
        jTextFieldfiltrealbum.setEnabled(false);
    }//GEN-LAST:event_jRadioButtonMusucienActionPerformed

    private void jRadioButtonProjetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonProjetActionPerformed
        jComboBoxInstru.setEnabled(true);
        jComboBoxAlbum.setEnabled(false);
        jComboBoxMusicien.setEnabled(false);
        jTextFieldfiltrealbum.setEnabled(false);
    }//GEN-LAST:event_jRadioButtonProjetActionPerformed

    private void jComboBoxInstruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxInstruActionPerformed
        Instru instru = (Instru) jComboBoxInstru.getSelectedItem();
        if(instru.getNom().contains("*")){
            myColloboModel.setMyList(daocollobo.selectCollobo());
        }else{
        myColloboModel.setMyList(daocollobo.selectColloboParInstru(instru));}
    }//GEN-LAST:event_jComboBoxInstruActionPerformed

    private void jComboBoxMusicienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxMusicienActionPerformed
        Musicien m = (Musicien) jComboBoxMusicien.getSelectedItem();
        if(m.getNom().contains("*")){
            myColloboModel.setMyList(daocollobo.selectCollobo());
        }else{
        myColloboModel.setMyList(daocollobo.selectColloboParMusicien(m));}
    }//GEN-LAST:event_jComboBoxMusicienActionPerformed

    private void jRadioButtonJourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonJourActionPerformed
        jComboBoxAlbum.setEnabled(true);
        jComboBoxInstru.setEnabled(false);
        jComboBoxMusicien.setEnabled(false);
        jTextFieldfiltrealbum.setEnabled(false);
    }//GEN-LAST:event_jRadioButtonJourActionPerformed

    private void jComboBoxAlbumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxAlbumActionPerformed
        Album album = (Album) jComboBoxAlbum.getSelectedItem();
        if(album.getTitre().contains("*")){
            myColloboModel.setMyList(daocollobo.selectCollobo());
        }else{
        myColloboModel.setMyList(daocollobo.selectColloboParAlbum(album));}
    }//GEN-LAST:event_jComboBoxAlbumActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
          if (evt.getClickCount() == 2) {
            // renvoie l'objet Collobo à passer en paramètre
            Collobo plan = (Collobo) myColloboModel.getMyList(jTable1.convertRowIndexToModel(jTable1.getSelectedRow()));
            // récupère la JFrame parente
            JFrame parent = (JFrame) (this.getDesktopPane().getTopLevelAncestor());
            new JDColloboUpdate(parent, "MODIFICATION Collaboration  ", plan);
            // après la modification : rafraîchir les données en relisant la BD
            myColloboModel.setMyList(daocollobo.selectCollobo());
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ArrayList<Collobo> list = daocollobo.selectCollobo();
        Collections.sort(list);
        myColloboModel.setMyList(list);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        ArrayList<Collobo> list = daocollobo.selectCollobo();
         Collections.sort(list);
        Collections.sort(list,Collections.reverseOrder());
        myColloboModel.setMyList(list); 
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextFieldfiltrealbumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldfiltrealbumActionPerformed
        ArrayList<Collobo>  that = new ArrayList<>();
        ArrayList<Collobo> list = daocollobo.selectCollobo();
         list.forEach((p) ->{
                String a = p.getAlbum().getTitre();
                String b = jTextFieldfiltrealbum.getText();
                if(a.contains(b)){
                    that.add(p);
                    myColloboModel.setMyList(that);
                }
            });
         myColloboModel.setMyList(that);
    }//GEN-LAST:event_jTextFieldfiltrealbumActionPerformed
    private void fillComponents() {
        /* charger toutes les projets */
        ArrayList<Instru> listInstru = daoInstru.selectInstru();
        listInstru.add(0, new Instru("-1", "*")); // ajoute une cat bidon : -1 signifie toutes les cat
        listInstru.forEach((p) -> {
            jComboBoxInstru.addItem(p); // on insère des objets dans les combo, mais ils sont affichés grâce à leurs méthodes toString() !
        });

        /* charger toutes les employe */
        ArrayList<Musicien> listMusicien = daoMusicien.selectMusicien();
        listMusicien.add(0, new Musicien(-1, "*"));
        listMusicien.forEach((p) -> {
            jComboBoxMusicien.addItem(p);
        });
        /* charger toutes les employe */
        ArrayList<Album> listalbum = daoAlbum.selectAlbum();
        listalbum.add(0, new Album(-1," * "));
        listalbum.forEach((j) -> {
            jComboBoxAlbum.addItem(j);
        });

        jComboBoxMusicien.setEnabled(false);
        jComboBoxInstru.setEnabled(false);
        jComboBoxAlbum.setEnabled(false);
        jRadioButtonfilter.setSelected(true);
        jTextFieldfiltrealbum.setEnabled(false);
       // jTextFieldfiltrealbum.setEnabled(false);
        myColloboModel.setMyList(daocollobo.selectCollobo());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonAddCollabo;
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JButton jButtonUpdateCollabo;
    private javax.swing.JComboBox jComboBoxAlbum;
    private javax.swing.JComboBox jComboBoxInstru;
    private javax.swing.JComboBox jComboBoxMusicien;
    private javax.swing.JLabel jLabelfilter;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButtonJour;
    private javax.swing.JRadioButton jRadioButtonMusucien;
    private javax.swing.JRadioButton jRadioButtonProjet;
    private javax.swing.JRadioButton jRadioButtonfilter;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldfiltrealbum;
    // End of variables declaration//GEN-END:variables
}
